# Generated by Django 2.2.16 on 2022-10-11 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_comment_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='Post',
            old_name='pub_date',
            new_name='created'
        ),
    ]
